title: Thalatta IO
email: redacted@redacted.com
description: In an world full of whales, containers and captains, we are the sea
repository: thalatta-io/thalatta-site
google_analytics: "UA-143041584-1"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-relative-links
  - jekyll-seo-tag
  - github-pages
